"""The ``khan://schema/main`` resource — comprehensive server reference.

Exposes a single Markdown document the agent can read *on demand*
when it needs detailed technical information about the calendar
server (the ``.ics`` file format, khal subcommand catalogue,
error-type taxonomy, debugging recipes, etc.). The schema is
loaded as a static string so the cost is one read per session
and there's no IPC involved.

Unlike ``prompts.primitives`` (which is content-injected into the
LLM context every time), ``resources/read`` is lazy — the agent
fetches only when it needs the canonical reference. This keeps
the per-prompt token count low while still giving the agent full
context on demand.
"""

from __future__ import annotations

from fastmcp import FastMCP

# A static Markdown reference. Reading a Markdown body directly via
# ``resources/read`` keeps the schema greppable and diffable.
_SCHEMA_DOCUMENT = """\
# percival-khan-calendar — schema reference (v0.3.0)

This document is the canonical technical reference for the
``percival-khan-calendar`` MCP server. The agent should fetch this
when:

* a tool returns an error class it doesn't recognise;
* the user asks about the on-disk layout;
* something previously-working is failing in a new environment
  (khal binary, locale, workspace path).

## 1. Storage layout

The calendar persists under ``$KHAN_WORKSPACE_DIR`` (default
``~/.nanobot/workspace/khalCalendar``):

```
khalCalendar/
├── khal.conf     # khal config, regenerated on drift
├── khal.db       # SQLite cache (khal internal)
├── calendar.lock # optional fcntl lock when KHAN_ENABLE_LOCK=true
└── data/
    └── nanobot/                  # default calendar name
        ├── <uuid>@percival-khan-calendar.ics
        ├── <uuid>@percival-khan-calendar.ics
        └── ...
```

Each event lives in its own ``.ics`` file (``VEVENT`` with a
single component) so updates are atomic and deletes are idempotent.

## 2. ``khal.conf``

Auto-regenerated by ``lifecycle.setup_workspace`` when absent
*or* drifted from the rendered template. The ``path`` field MUST
equal ``$KHAN_WORKSPACE_DIR/data/$KHAN_DEFAULT_CALENDAR`` — khal's
vdir reader is **non-recursive**, so pointing one level above
the adapter's writes will hide every event from ``khal list``.

## 3. Datetime and timezone

All on-disk DTSTART/DTEND values are emitted in the RFC-5545
canonical form ``YYYYMMDDTHHMMSSZ`` (round-6 / S6 fix). A naive
``datetime(2026, 12, 25, 14, 30)`` is interpreted as local time by
the adapter and stored in UTC. ``icalendar`` properties mutated
via ``ev["x"] = value`` would silently pick the ``+00:00`` form
— we use ``.add(...)`` exclusively to keep the canonical form.

## 4. Documented quirks

### khal 0.14.0 — relative windows can be TZ-dependent

Prefer ``start_date="DD/MM/YYYY", range_or_end="7d"`` over
``start_date="today", range_or_end="7d"`` whenever the absolute
timestamp matters. The ``khal list tomorrow 1d`` calculation can
place events outside the window if the local TZ != the container
TZ (issue 2026-07-22, Pós-fix #2).

### khal 0.14.0 — printcalendars is name-only

``khal printcalendars`` returns the calendar name from
``khal.conf``, not the event count. Use ``khan_list_calendars``
or ``khan_get_status`` for accurate counts.

## 5. Error taxonomy

| Exception class | Recoverable? | Common cause |
|-----------------|--------------|--------------|
| ``KhanValidationError``       | yes | invalid time expression, control chars, leading-dash arg |
| ``KhanNotFoundError``        | n/a | no match for ``exact_term`` |
| ``KhanAmbiguousMatchError``  | yes | multiple matches; refine query |
| ``KhanInfrastructureError``  | no  | khal binary missing, timeout, OS error |

Tools marshal these as **string** returns prefixed with
``[recoverable_by_agent=false]`` when the exception is not
recoverable, or with a leading descriptive line when it is.

## 6. Permissions / path-traversal

* The ``calendar=`` field is validated by ``_validate_calendar_name``:
  rejects separators, leading dot, anything outside
  ``[A-Za-z0-9_.-]{1,64}`` (defence-in-depth; today the tool layer
  hardcodes ``DEFAULT_CALENDAR``).
* ``khan_export_ics(output_path=...)`` rejects output outside
  ``$KHAN_WORKSPACE_DIR`` and refuses symlinks (security round 1).
* All free-text inputs go through a Pydantic argument-injection
  guard (rejects ``-`` prefix and ``--`` substring) plus a control-
  character sanitizer (security round 3).

## 7. Testing modes

| Marker | Behaviour | Requires khal binary |
|--------|-----------|----------------------|
| (default) | unit tests + mocked subprocess | no |
| ``-m integration`` | real ``khal`` CLI invoked end-to-end | yes |

The integration tests are NOT in CI by default because they need
``khal`` installed in PATH. Run them locally after a refactor that
touches the khal adapter or the khal.conf template.

## 7.5. Prompts and resources (v0.3.0)

The server registers six ``prompts.primitives`` (visible via
``prompts/list``) and one resource (visible via ``resources/list``).
These are *oriented* guidance for the agent, not part of the tool
contract.

Prompts:

| Name | Arg | Purpose |
|------|-----|---------|
| ``khan_overview``                  | — | Server tour + recommended workflow |
| ``khan_create_event_semantics``    | — | Time/alarm/recurrence field syntax |
| ``khan_update_workflow``           | — | UID / RRULE / VALARM preservation |
| ``khan_delete_with_confirmation``  | — | Two-call dry-run + confirm protocol |
| ``khan_search_strategy``           | ``keyword: str``, ``scope: Literal[...]`` (default ``"summary"``) | Field-qualified search |
| ``khan_quick_action_quick_create`` | ``user_intent: str`` | Verbatim echo + PT-BR date mapping |

Resource:

| URI                       | MIME              | Body                                       |
|---------------------------|-------------------|--------------------------------------------|
| ``khan://schema/main``    | ``text/markdown`` | This document. Read on demand. |

Boot re-entrancy: ``server.main()`` constructs a fresh
``FastMCP`` instance per invocation. Tests that need strict
isolation should likewise call ``register_prompts`` and
``register_resources`` against a freshly-constructed ``FastMCP``
instance — re-using the same instance twice will log
``Component already exists: prompt:<name>@`` but not raise (this
is FastMCP 3.4 behaviour, not a server bug).

## 8. Where things live in the codebase

```
src/percival_khan_calendar/
├── constants.py            # all Final[Path] / Final[str] knobs
├── exceptions.py           # 4 typed exceptions
├── lifecycle.py            # setup_workspace + auto-heal
├── security.py             # envelope_untrusted_data + argument guard
├── server.py               # FastMCP entrypoint (fresh instance per boot)
├── models.py               # Pydantic validators (PII defence)
├── adapters/
│   ├── khal_adapter.py         # file-level read/write + UID + canonical-Z
│   ├── locks.py                # workspace_lock context manager
│   └── subprocess_runner.py    # executar_comando_khal + env passing
├── tools/
│   ├── create_event.py         # khan_create_event
│   ├── delete_event.py         # khan_delete_event + khan_delete_event_safe
│   ├── list_events.py          # khan_list_events + khan_get_event + khan_search_events
│   ├── export_ics.py           # khan_export_ics
│   ├── status.py               # khan_get_status + khan_list_calendars
│   ├── update_event.py         # khan_update_event
│   ├── view.py                 # khan_view_agenda + khan_view_calendar
│   └── prompts.py              # 6 prompts (khan_overview, …)
└── resources/
    └── docs.py                 # khan://schema/main (this document)
```
"""

# Resource URI is constant — keep public for tests.
SCHEMA_URI = "khan://schema/main"
SCHEMA_MIME = "text/markdown"


def register_resources(mcp: FastMCP) -> None:
    """Register the static reference at ``khan://schema/main``.

    Note: FastMCP 3.4 raises ``ValueError`` if a resource is
    re-registered with the same URI. Callers that need to
    re-initialise the server must create a fresh ``FastMCP``
    instance. Production code only calls this once during boot.
    """

    @mcp.resource(
        uri=SCHEMA_URI,
        name="percival-khan-calendar schema reference",
        description=(
            "Canonical technical reference for the calendar MCP server. "
            "Read this once per session when you need detailed information "
            "about storage layout, khal.conf format, datetime semantics, "
            "error taxonomy, or the codebase map."
        ),
        mime_type=SCHEMA_MIME,
        tags={"reference", "documentation"},
    )
    def schema_reference() -> str:
        # The resource body is a static string; no parameters, no
        # side-effects. Returning ``str`` is automatically wrapped by
        # FastMCP into the protocol-correct ``ReadResourceResult``.
        return _SCHEMA_DOCUMENT


__all__ = ["register_resources", "SCHEMA_URI", "SCHEMA_MIME"]
